spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smsgw_demo?zeroDateTimeBehavior=convertToNull
    username: root
    password: bodrul
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
  file:
    name: momagic.log.txt
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
